// ============================================================
// DATA LAYER — chỉnh sửa nội dung tại đây, không cần đụng UI
// ============================================================

export const siteConfig = {
  name: "Phạm Thanh Tùng",
  tagline: "Nhà Hoạch Định",
  vision:
    "Tạo tác động để Việt Nam định vị là quốc gia Du lịch Nông nghiệp.",
  email: "nhahoachdinh.ptt@gmail.com",
  phone: "0935 396 705",
  address: "79 Ngô Mây, Cẩm Lệ, Đà Nẵng",
  social: {
    facebook: "https://www.facebook.com/NhaHoachDinhPhamThanhTung",
    youtube: "https://www.youtube.com/@NhaHoachDinhPhamThanhTung",
    pinterest: "https://pin.it/4ZOSKcq8T",
  },
};

export const navLinks = [
  { label: "Về Tôi", href: "/ve-toi" },
  { label: "Tôi Làm", href: "/toi-lam" },
  { label: "Chia Sẻ", href: "/chia-se-kien-thuc" },
  { label: "Sách Farmstay", href: "/sach-farmstay" },
  { label: "Thông Tin", href: "/lien-he" },
];

export const missions = [
  {
    icon: "🗺️",
    label: "Hoạch Định Vùng Đất",
    title: "Biến Mỗi Vùng Đất Thành Tương Lai",
    body: "Hơn 12 năm quy hoạch và phát triển tổng thể vùng đất nông nghiệp — từ Đắk Nông, Quảng Nam đến khắp các tỉnh thành Việt Nam. Mình giúp nhà đầu tư nhìn thấy tiềm năng ẩn trong từng mảnh đất trước khi bất kỳ ai khác nhận ra.",
    img: "/images/mission-1.jpg",
    imgAlt: "Hoạch định phát triển vùng đất",
    imgRight: false,
    bg: "bg-white",
  },
  {
    icon: "🧭",
    label: "Tư Vấn Chiến Lược",
    title: "Kiến Tạo Farmstay Bền Vững",
    body: "Hơn 100 dự án farmstay & du lịch sinh thái được tư vấn trên toàn quốc — từ Hana Land Ecostay Đà Lạt, Sản Việt Farm Khánh Hòa, đến Muonglo Farmstay Yên Bái. Mỗi dự án là một hành trình riêng, cần chiến lược riêng.",
    img: "/images/mission-2.jpg",
    imgAlt: "Tư vấn chiến lược farmstay",
    imgRight: true,
    bg: "bg-white",
  },
  {
    icon: "🌐",
    label: "Xây Dựng Hệ Sinh Thái",
    title: "Kết Nối Cộng Đồng Farmstay Việt Nam",
    body: "Sáng lập Xuyên Việt Farmstay — hành trình 4 mùa (2021, 2023, 2024, 2025) kết nối hơn 100 farm/farmstay toàn quốc. Cùng Farmstay Update — nền tảng tri thức cấp quốc gia, hội tụ chuyên gia hàng đầu về hoạch định vùng đất.",
    img: "/images/mission-3.jpg",
    imgAlt: "Xuyên Việt Farmstay",
    imgRight: false,
    bg: "bg-beige/30",
  },
  {
    icon: "👥",
    label: "Dẫn Dắt Cộng Đồng",
    title: "Trao Quyền Cho Địa Phương",
    body: "Tổ chức hơn 30+ hội thảo, tọa đàm tại Hà Nội, Quảng Nam, Đắk Lắk, Gia Lai, Quảng Ngãi, Huế... Đào tạo cán bộ công chức, cấy nền farmstay bền vững — tạo sinh kế lâu dài cho cộng đồng địa phương.",
    img: "/images/mission-4.jpg",
    imgAlt: "Dẫn dắt cộng đồng",
    imgRight: true,
    bg: "bg-beige/30",
  },
];

export const companies = [
  {
    name: "DEFARM",
    role: "CEO & Founder",
    description: "Tư vấn, Thiết kế & Quản trị Farmstay chuyên nghiệp",
    logo: "",
    href: "/lien-he",
  },
  {
    name: "MASTERY",
    role: "CEO & Founder",
    description: "Hoạch định Chiến lược Đầu tư Dự án nông nghiệp sinh thái",
    logo: "",
    href: "/lien-he",
  },
  {
    name: "HTX Khe Sanh",
    role: "Cố Vấn Chiến Lược",
    description: "Truyền lửa, chuyển giao tri thức vào vùng đất — Mô hình HTX tiên phong",
    logo: "",
    href: "/lien-he",
  },
  {
    name: "Xuyên Việt Farmstay",
    role: "Nhà Sáng Lập",
    description: "Hành trình kết nối cộng đồng Farmstay toàn quốc — 4 mùa, 100+ điểm đến",
    logo: "",
    href: "/ve-toi",
  },
];

export const testimonials = [
  {
    name: "Chủ Đầu Tư Farmstay",
    role: "Yên Bái",
    avatar: "",
    content:
      "Anh Tùng đã giúp tôi định hình lại toàn bộ mô hình kinh doanh farmstay. Từ một khu đất hoang, chúng tôi đã xây dựng được một điểm đến du lịch thu hút hàng nghìn khách mỗi năm.",
  },
  {
    name: "Nhà Đầu Tư BĐS Nông Nghiệp",
    role: "Đà Lạt",
    avatar: "",
    content:
      "Sự hiểu biết sâu sắc về cả chiến lược lẫn kinh tế nông nghiệp của anh Tùng là điều hiếm thấy. Những tư vấn của anh đã giúp dự án của tôi tránh được nhiều rủi ro nghiêm trọng và đúng hướng ngay từ đầu.",
  },
  {
    name: "Giám Đốc HTX Nông Nghiệp",
    role: "Khánh Hòa",
    avatar: "",
    content:
      "Phương pháp tiếp cận hệ thống của anh Tùng — từ đất đai, con người đến thị trường — đã tạo ra bước ngoặt thực sự cho hợp tác xã chúng tôi. Chúng tôi không còn hoạt động đơn lẻ nữa.",
  },
];

export const pressItems = [
  {
    name: "Tuổi Trẻ",
    title: "Vì sao nhiều người đầu tư homestay, farmstay thất bại chóng vánh?",
    href: "https://tuoitre.vn/vi-sao-nhieu-nguoi-dau-tu-homestay-farmstay-that-bai-chong-vanh-20250819145343618.htm",
  },
  {
    name: "CafeBiz",
    title: "Việt Nam có đầy đủ tiềm năng để trở thành quốc gia farmstay",
    href: "https://cafebiz.vn/kts-pham-thanh-tung-viet-nam-co-day-du-tiem-nang-ve-thien-nhien-va-con-nguoi-de-tro-thanh-mot-quoc-gia-farmstay-20200928192118412.chn",
  },
  {
    name: "Tiền Phong",
    title: "Kiến trúc sư thuận tự nhiên",
    href: "https://tienphong.vn/gioi-tre/kien-truc-su-thuan-tu-nhien-1717276.tpo",
  },
  {
    name: "The Leader",
    title: "Đất nông nghiệp thành vàng nhờ du lịch: Cơ hội hay cạm bẫy?",
    href: "https://theleader.vn/dat-nong-nghiep-thanh-vang-nho-du-lich-co-hoi-hay-cam-bay-d41697.html",
  },
  {
    name: "Reatimes",
    title: "Xu hướng phát triển farmstay nhìn từ tiềm năng BĐS nông nghiệp",
    href: "https://reatimes.vn/xu-huong-phat-trien-farmstay-nhin-tu-tiem-nang-bds-nong-nghiep-1597387193831.html",
  },
  {
    name: "TBTC Việt Nam",
    title: "BĐS du lịch nông nghiệp — phân khúc nhiều tiềm năng",
    href: "https://thoibaotaichinhvietnam.vn/bat-dong-san-du-lich-nong-nghiep-phan-khuc-nhieu-tiem-nang-127352.html",
  },
  {
    name: "Cafeland",
    title: "Farmstay trước cơn lốc phân lô bán nền",
    href: "https://cafeland.vn/tin-tuc/farmstay-truoc-con-loc-phan-lo-ban-nen-89860.html",
  },
  {
    name: "Báo Quảng Nam",
    title: "Nông Sơn: Hội thảo giới thiệu tiềm năng du lịch Đại Bình",
    href: "https://baoquangnam.vn/du-lich/nong-son-hoi-thao-gioi-thieu-tiem-nang-du-lich-dai-binh-111408.html",
  },
];

export interface Article {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  image: string;
  readTime: number;
}

export const articles: Article[] = [
  {
    slug: "nhung-thach-thuc-phai-luu-tam-khi-dau-tu-farmstay",
    title: "NHỮNG THÁCH THỨC PHẢI LƯU TÂM KHI ĐẦU TƯ FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: những thách thức phải lưu tâm khi đầu tư farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2024-02-27",
    image: "/images/outdoor-2-garden-speaking.jpg",
    readTime: 10,
  },
  {
    slug: "tiem-nang-va-thach-thuc-khi-dau-tu-farmstay-o-cac-tinh-tay-bac",
    title: "TIỀM NĂNG VÀ THÁCH THỨC KHI ĐẦU TƯ FARMSTAY Ở CÁC TỈNH TÂY BẮC",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: tiềm năng và thách thức khi đầu tư farmstay ở các tỉnh tây bắc. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2024-02-28",
    image: "/images/outdoor-1-mountain-tea.jpg",
    readTime: 12,
  },
  {
    slug: "farmstay-ket-hop-spa-mot-dang-cap-moi-trong-nganh-lam-dep",
    title: "FARMSTAY KẾT HỢP SPA - MỘT ĐẲNG CẤP MỚI TRONG NGÀNH LÀM ĐẸP",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay kết hợp spa - một đẳng cấp mới trong ngành làm đẹp. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2024-02-29",
    image: "/images/fs-portrait-bamboo.jpg",
    readTime: 11,
  },
  {
    slug: "cac-buoc-chuyen-doi-khu-lich-sinh-thai-qua-farmstay",
    title: "CÁC BƯỚC CHUYỂN ĐỔI KHU LỊCH SINH THÁI QUA FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: các bước chuyển đổi khu lịch sinh thái qua farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2024-03-01",
    image: "/images/outdoor-3-forest-stream.jpg",
    readTime: 11,
  },
  {
    slug: "can-chuan-bi-ky-nang-gi-de-phat-trien-mot-farmstay",
    title: "CẦN CHUẨN BỊ KỸ NĂNG GÌ ĐỂ PHÁT TRIỂN MỘT FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: cần chuẩn bị kỹ năng gì để phát triển một farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2024-03-02",
    image: "/images/fs-windmill.jpg",
    readTime: 11,
  },
  {
    slug: "lam-cach-nao-giai-quyet-bai-toan-duoc-gia-mat-mua-va-duoc-mua-mat-gia-cua-nong-s",
    title: "LÀM CÁCH NÀO GIẢI QUYẾT BÀI TOÁN ĐƯỢC GIÁ MẤT MÙA VÀ ĐƯỢC MÙA MẤT GIÁ CỦA NÔNG SẢN VIỆT NAM",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: làm cách nào giải quyết bài toán được giá mất mùa và được mùa mất giá của nông sản việt nam. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Tài Chính",
    date: "2024-03-03",
    image: "/images/outdoor-4-waterfall.jpg",
    readTime: 15,
  },
  {
    slug: "muoi-tieu-chi-chon-dat-lam-farmstay",
    title: "MƯỜI TIÊU CHÍ CHỌN ĐẤT LÀM FARMSTAY.",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: mười tiêu chí chọn đất làm farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2024-03-04",
    image: "/images/outdoor-5-garden-chair.jpg",
    readTime: 9,
  },
  {
    slug: "cac-buoc-nen-lam-khi-moi-mua-dat-lam-farmstay",
    title: "CÁC BƯỚC NÊN LÀM KHI MỚI MUA ĐẤT LÀM FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: các bước nên làm khi mới mua đất làm farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2024-03-07",
    image: "/images/fs-outdoor-field.jpg",
    readTime: 10,
  },
  {
    slug: "ba-nguon-luc-chinh-cho-giai-doan-dau-cua-farmstay-viet-tiep-bai-viet-cac-buoc-ne",
    title: "BA NGUỒN LỰC CHÍNH CHO GIAI ĐOẠN ĐẦU CỦA FARMSTAY VIẾT TIẾP BÀI VIẾT \"CÁC BƯỚC NÊN LÀM KHI MỚI MUA ĐẤT LÀM FARMSTAY\"",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: ba nguồn lực chính cho giai đoạn đầu của farmstay viết tiếp bài viết \"các bước nên làm khi mới mua đất làm farmstay\". Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2024-03-08",
    image: "/images/fs-interview-mountain.jpg",
    readTime: 15,
  },
  {
    slug: "tai-sao-viet-nam-can-tro-thanh-quoc-gia-du-lich-nong-nghiep",
    title: "TẠI SAO VIỆT NAM CẦN TRỞ THÀNH QUỐC GIA DU LỊCH NÔNG NGHIỆP.",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: tại sao việt nam cần trở thành quốc gia du lịch nông nghiệp. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2024-03-09",
    image: "/images/portrait-stage-1.jpg",
    readTime: 12,
  },
  {
    slug: "nhung-tu-duy-dung-de-tu-thiet-ke-tong-the-farmstay",
    title: "NHỮNG TƯ DUY ĐÚNG ĐỂ TỰ THIẾT KẾ TỔNG THỂ FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: những tư duy đúng để tự thiết kế tổng thể farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Thiết Kế",
    date: "2024-03-10",
    image: "/images/outdoor-2-garden-speaking.jpg",
    readTime: 11,
  },
  {
    slug: "y-tuong-mo-hinh-farmstay-va-tinh-than-homestead",
    title: "Ý TƯỞNG MÔ HÌNH FARMSTAY VÀ TINH THẦN HOMESTEAD",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: ý tưởng mô hình farmstay và tinh thần homestead. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2024-03-11",
    image: "/images/outdoor-1-mountain-tea.jpg",
    readTime: 10,
  },
  {
    slug: "phap-ly-cho-farmstay",
    title: "PHÁP LÝ CHO FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: pháp lý cho farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2024-03-12",
    image: "/images/fs-portrait-bamboo.jpg",
    readTime: 8,
  },
  {
    slug: "homestead-phong-cach-song-xanh-hoi-sinh-loi-song-xanh",
    title: "HOMESTEAD PHONG CÁCH SỐNG XANH, HỒI SINH LỐI SỐNG XANH.",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: homestead phong cách sống xanh, hồi sinh lối sống xanh. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2024-03-13",
    image: "/images/outdoor-3-forest-stream.jpg",
    readTime: 11,
  },
  {
    slug: "luu-y-nhung-gi-de-co-farmstay-ben-vung",
    title: "LƯU Ý NHỮNG GÌ ĐỂ CÓ FARMSTAY BỀN VỮNG",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: lưu ý những gì để có farmstay bền vững. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-08-08",
    image: "/images/fs-windmill.jpg",
    readTime: 9,
  },
  {
    slug: "sau-canh-bao-chinh-tu-duy-lam-ban-chac-chan-thua-cuoc-khi-dau-tu-farmstay",
    title: "SÁU CẢNH BÁO CHÍNH: TƯ DUY LÀM BẠN CHẮC CHẮN THUA CUỘC KHI ĐẦU TƯ FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: sáu cảnh báo chính: tư duy làm bạn chắc chắn thua cuộc khi đầu tư farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-08-09",
    image: "/images/outdoor-4-waterfall.jpg",
    readTime: 13,
  },
  {
    slug: "tuong-lai-farmstay-viet-nam-5-nam-toi-mo-hinh-nao-se-len-ngoi",
    title: "TƯƠNG LAI FARMSTAY VIỆT NAM: 5 NĂM TỚI, MÔ HÌNH NÀO SẼ \"LÊN NGÔI\"",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: tương lai farmstay việt nam: 5 năm tới, mô hình nào sẽ \"lên ngôi\". Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-08-11",
    image: "/images/outdoor-5-garden-chair.jpg",
    readTime: 12,
  },
  {
    slug: "ban-dang-phat-trien-mot-farmstay-hay-tao-nen-cai-bay-tai-chinh-cho-chinh-minh",
    title: "BẠN ĐANG PHÁT TRIỂN MỘT FARMSTAY HAY TẠO NÊN CÁI BẪY TÀI CHÍNH CHO CHÍNH MÌNH?",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: bạn đang phát triển một farmstay hay tạo nên cái bẫy tài chính cho chính mình?. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Tài Chính",
    date: "2025-08-14",
    image: "/images/fs-outdoor-field.jpg",
    readTime: 13,
  },
  {
    slug: "nguyen-nhan-nao-khien-cac-nha-dau-tu-mo-hinh-farmstay-dot-tien-phi-ly-khi-khoi-n",
    title: "NGUYÊN NHÂN NÀO KHIẾN CÁC NHÀ ĐẦU TƯ MÔ HÌNH FARMSTAY ĐỐT TIỀN PHI LÝ KHI KHỞI NGHIỆP?",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: nguyên nhân nào khiến các nhà đầu tư mô hình farmstay đốt tiền phi lý khi khởi nghiệp?. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-08-16",
    image: "/images/fs-interview-mountain.jpg",
    readTime: 14,
  },
  {
    slug: "lo-trinh-gia-tang-gia-tri-cho-bat-dong-san-nong-nghiep",
    title: "LỘ TRÌNH GIA TĂNG GIÁ TRỊ CHO BẤT ĐỘNG SẢN NÔNG NGHIỆP",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: lộ trình gia tăng giá trị cho bất động sản nông nghiệp. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2025-08-22",
    image: "/images/portrait-stage-1.jpg",
    readTime: 11,
  },
  {
    slug: "quoc-khanh-29-viet-nam-hung-cuong-tu-noi-luc-du-lich-nong-nghiep",
    title: "QUỐC KHÁNH 2/9: VIỆT NAM HÙNG CƯỜNG TỪ NỘI LỰC DU LỊCH NÔNG NGHIỆP",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: quốc khánh 2/9: việt nam hùng cường từ nội lực du lịch nông nghiệp. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Cộng Đồng",
    date: "2025-09-02",
    image: "/images/outdoor-2-garden-speaking.jpg",
    readTime: 12,
  },
  {
    slug: "farmstay-can-lam-gi-khi-bien-doi-khi-hau-bat",
    title: "FARMSTAY CẦN LÀM GÌ KHI BIẾN ĐỔI KHÍ HẬU BẤT",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay cần làm gì khi biến đổi khí hậu bất. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-09-03",
    image: "/images/outdoor-1-mountain-tea.jpg",
    readTime: 10,
  },
  {
    slug: "farmstay-tu-tap",
    title: "FARMSTAY TU TẬP",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay tu tập. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-09-06",
    image: "/images/fs-portrait-bamboo.jpg",
    readTime: 7,
  },
  {
    slug: "luu-y-chon-dat-phat-trien-va-sai-lam-khi-lam-farmstay",
    title: "LƯU Ý CHỌN ĐẤT PHÁT TRIỂN VÀ SAI LẦM KHI LÀM FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: lưu ý chọn đất phát triển và sai lầm khi làm farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2025-09-12",
    image: "/images/outdoor-3-forest-stream.jpg",
    readTime: 11,
  },
  {
    slug: "tai-sao-tour-du-lich-nong-nghiep-kho-hay-it-nguoi-thiet-ke-duoc",
    title: "TẠI SAO TOUR DU LỊCH NÔNG NGHIỆP KHÓ HAY ÍT NGƯỜI THIẾT KẾ ĐƯỢC",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: tại sao tour du lịch nông nghiệp khó hay ít người thiết kế được. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Thiết Kế",
    date: "2025-09-15",
    image: "/images/fs-windmill.jpg",
    readTime: 12,
  },
  {
    slug: "nguyen-tac-chon-cay-trong-trong-farmstay",
    title: "NGUYÊN TẮC CHỌN CÂY TRỒNG TRONG FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: nguyên tắc chọn cây trồng trong farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-09-22",
    image: "/images/outdoor-4-waterfall.jpg",
    readTime: 10,
  },
  {
    slug: "xay-dung-noi-luc",
    title: "XÂY DỰNG NỘI LỰC",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: xây dựng nội lực. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Cộng Đồng",
    date: "2025-01-0 01",
    image: "/images/outdoor-5-garden-chair.jpg",
    readTime: 7,
  },
  {
    slug: "ao-mong-bo-pho-ve-rung-va-nhung-su-that-khong-may-ai-dam-noi-ve-farmstay",
    title: "ẢO MỘNG \"BỎ PHỐ VỀ RỪNG\" VÀ NHỮNG SỰ THẬT KHÔNG MẤY AI DÁM NÓI VỀ FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: ảo mộng \"bỏ phố về rừng\" và những sự thật không mấy ai dám nói về farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-01-0 28",
    image: "/images/fs-outdoor-field.jpg",
    readTime: 13,
  },
  {
    slug: "gia-tri-phap-ly-trong-farmstay-rao-can-la-dai-duong-xanh-va-nuoc-di-chien-luoc",
    title: "GIÁ TRỊ PHÁP LÝ TRONG FARMSTAY: RÀO CẢN LÀ ĐẠI DƯƠNG XANH VÀ NƯỚC ĐI CHIẾN LƯỢC",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: giá trị pháp lý trong farmstay: rào cản là đại dương xanh và nước đi chiến lược. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2025-01-1 02",
    image: "/images/fs-interview-mountain.jpg",
    readTime: 13,
  },
  {
    slug: "nhung-luu-y-khi-tim-don-vi-thiet-ke-cho-farmstay",
    title: "NHỮNG LƯU Ý KHI TÌM ĐƠN VỊ THIẾT KẾ CHO FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: những lưu ý khi tìm đơn vị thiết kế cho farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Thiết Kế",
    date: "2025-01-1 07",
    image: "/images/portrait-stage-1.jpg",
    readTime: 10,
  },
  {
    slug: "farmstay-la-tien-than-cua-ecovillage-kien-tao-di-san-ben-vung-trong-boi-canh-bie",
    title: "FARMSTAY LÀ TIỀN THÂN CỦA ECOVILLAGE: KIẾN TẠO DI SẢN BỀN VỮNG TRONG BỐI CẢNH BIẾN ĐỔI KHÍ HẬU",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay là tiền thân của ecovillage: kiến tạo di sản bền vững trong bối cảnh biến đổi khí hậu. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-01-1 09",
    image: "/images/outdoor-2-garden-speaking.jpg",
    readTime: 15,
  },
  {
    slug: "lam-farmstay-de-co-khach-hay-co-khach-roi-moi-lam-farmstay",
    title: "LÀM FARMSTAY ĐỂ CÓ KHÁCH HAY CÓ KHÁCH RỒI MỚI LÀM FARMSTAY?",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: làm farmstay để có khách hay có khách rồi mới làm farmstay?. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-01-1 13",
    image: "/images/outdoor-1-mountain-tea.jpg",
    readTime: 11,
  },
  {
    slug: "ban-chat-cua-tri-thuy-va-quan-tri-nuoc-vi-hieu-sai-nen-lu-lut-lon",
    title: "BẢN CHẤT CỦA TRỊ THỦY VÀ QUẢN TRỊ NƯỚC, VÌ HIỂU SAI NÊN LŨ LỤT LỚN",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: bản chất của trị thủy và quản trị nước, vì hiểu sai nên lũ lụt lớn. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-01-1 20",
    image: "/images/fs-portrait-bamboo.jpg",
    readTime: 12,
  },
  {
    slug: "hanh-trinh-7-nam-tang-truong-nong-va-thanh-loc-khac-nghiet-cua-mo-hinh-farmstay-",
    title: "HÀNH TRÌNH 7 NĂM \"TĂNG TRƯỞNG NÓNG VÀ THANH LỌC KHẮC NGHIỆT\" CỦA MÔ HÌNH FARMSTAY VIỆT NAM",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: hành trình 7 năm \"tăng trưởng nóng và thanh lọc khắc nghiệt\" của mô hình farmstay việt nam. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2025-01-2 18",
    image: "/images/outdoor-3-forest-stream.jpg",
    readTime: 15,
  },
  {
    slug: "tu-duy-moi-ve-bat-dong-san-gan-voi-du-lich-nong-thon",
    title: "TƯ DUY MỚI VỀ BẤT ĐỘNG SẢN GẮN VỚI DU LỊCH NÔNG THÔN",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: tư duy mới về bất động sản gắn với du lịch nông thôn. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2025-01-2 20",
    image: "/images/fs-windmill.jpg",
    readTime: 11,
  },
  {
    slug: "hieu-chua-du-ve-phap-ly-nguy-co-mat-du-an-hay-mat-dat-farmstay",
    title: "HIỂU CHƯA ĐỦ VỀ PHÁP LÝ: NGUY CƠ MẤT DỰ ÁN HAY MẤT ĐẤT FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: hiểu chưa đủ về pháp lý: nguy cơ mất dự án hay mất đất farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2025-01-2 21",
    image: "/images/outdoor-4-waterfall.jpg",
    readTime: 12,
  },
  {
    slug: "dinh-huong-farmstay-nho-can-lam-nhung-gi-ban-dau",
    title: "ĐỊNH HƯỚNG FARMSTAY NHỎ: CẦN LÀM NHỮNG GÌ BAN ĐẦU?",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: định hướng farmstay nhỏ: cần làm những gì ban đầu?. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-01-10",
    image: "/images/outdoor-5-garden-chair.jpg",
    readTime: 11,
  },
  {
    slug: "8-quy-tac-trong-quy-hoach-farmstay-dong-bang",
    title: "8 QUY TẮC TRONG QUY HOẠCH FARMSTAY ĐỒNG BẰNG",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: 8 quy tắc trong quy hoạch farmstay đồng bằng. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Thiết Kế",
    date: "2026-01-12",
    image: "/images/fs-outdoor-field.jpg",
    readTime: 10,
  },
  {
    slug: "farmstay-khong-phai-lam-cho-dep-de-chup-hinh-check-in",
    title: "FARMSTAY KHÔNG PHẢI \"LÀM CHO ĐẸP\" ĐỂ CHỤP HÌNH CHECK-IN",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay không phải \"làm cho đẹp\" để chụp hình check-in. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-01-14",
    image: "/images/fs-interview-mountain.jpg",
    readTime: 11,
  },
  {
    slug: "xu-huong-phat-trien-du-lich-viet-nam-len-rung-hay-xuong-bien",
    title: "XU HƯỚNG PHÁT TRIỂN DU LỊCH VIỆT NAM: LÊN RỪNG HAY XUỐNG BIỂN?",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: xu hướng phát triển du lịch việt nam: lên rừng hay xuống biển?. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-01-16",
    image: "/images/portrait-stage-1.jpg",
    readTime: 12,
  },
  {
    slug: "dieu-kien-gi-dan-toi-su-thanh-cong-cua-mot-farmstay",
    title: "ĐIỀU KIỆN GÌ DẪN TỚI SỰ THÀNH CÔNG CỦA MỘT FARMSTAY?",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: điều kiện gì dẫn tới sự thành công của một farmstay?. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-01-22",
    image: "/images/outdoor-2-garden-speaking.jpg",
    readTime: 11,
  },
  {
    slug: "nhung-goi-y-ve-kieu-kien-truc-cho-farmstay-tren-dia-hinh-doi-doc",
    title: "NHỮNG GỢI Ý VỀ KIỂU KIẾN TRÚC CHO FARMSTAY TRÊN ĐỊA HÌNH ĐỒI DỐC",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: những gợi ý về kiểu kiến trúc cho farmstay trên địa hình đồi dốc. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Thiết Kế",
    date: "2026-01-24",
    image: "/images/outdoor-1-mountain-tea.jpg",
    readTime: 12,
  },
  {
    slug: "goi-y-trai-nghiem-cho-farmstay-tu-kich-ban-den-dong-tien-ben-vung",
    title: "GỢI Ý TRẢI NGHIỆM CHO FARMSTAY: TỪ \"KỊCH BẢN\" ĐẾN \"DÒNG TIỀN\" BỀN VỮNG",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: gợi ý trải nghiệm cho farmstay: từ \"kịch bản\" đến \"dòng tiền\" bền vững. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Tài Chính",
    date: "2026-02-13",
    image: "/images/fs-portrait-bamboo.jpg",
    readTime: 13,
  },
  {
    slug: "kich-ban-trai-nghiem-chia-khoa-vang-quyet-dinh-gia-tri-tour-farmstay",
    title: "KỊCH BẢN TRẢI NGHIỆM: \"CHÌA KHÓA VÀNG\" QUYẾT ĐỊNH GIÁ TRỊ TOUR FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: kịch bản trải nghiệm: \"chìa khóa vàng\" quyết định giá trị tour farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Marketing",
    date: "2026-02-14",
    image: "/images/outdoor-3-forest-stream.jpg",
    readTime: 13,
  },
  {
    slug: "farmstay-huan-luyen-buoc-di-chien-luoc-dot-pha-cho-nha-dao-tao-va-chu-doanh-nghi",
    title: "FARMSTAY HUẤN LUYỆN: BƯỚC ĐI CHIẾN LƯỢC ĐỘT PHÁ CHO NHÀ ĐÀO TẠO VÀ CHỦ DOANH NGHIỆP CÓ TẦM",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay huấn luyện: bước đi chiến lược đột phá cho nhà đào tạo và chủ doanh nghiệp có tầm. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-02-15",
    image: "/images/fs-windmill.jpg",
    readTime: 15,
  },
  {
    slug: "farmstay-danh-cho-tre-em-chien-luoc-ngach-de-thoat-khoi-dai-duong-do",
    title: "FARMSTAY DÀNH CHO TRẺ EM: CHIẾN LƯỢC \"NGÁCH\" ĐỂ THOÁT KHỎI ĐẠI DƯƠNG ĐỎ",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay dành cho trẻ em: chiến lược \"ngách\" để thoát khỏi đại dương đỏ. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-02-16",
    image: "/images/outdoor-4-waterfall.jpg",
    readTime: 13,
  },
  {
    slug: "farmstay-nghe-thuat-san-khau-thuc-canh-de-dinh-vi-thuong-hieu-ca-nhan-dinh-cao",
    title: "FARMSTAY NGHỆ THUẬT: SÂN KHẤU THỰC CẢNH ĐỂ ĐỊNH VỊ THƯƠNG HIỆU CÁ NHÂN ĐỈNH CAO",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay nghệ thuật: sân khấu thực cảnh để định vị thương hiệu cá nhân đỉnh cao. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Marketing",
    date: "2026-02-17",
    image: "/images/outdoor-5-garden-chair.jpg",
    readTime: 13,
  },
  {
    slug: "farmstay-suc-khoe-du-lich-suc-khoe-tam-nhin-moi-cho-ky-nguyen-cham-soc-the-chat-",
    title: "FARMSTAY SỨC KHỎE - DU LỊCH SỨC KHỎE: TẦM NHÌN MỚI CHO KỶ NGUYÊN CHĂM SÓC THỂ CHẤT VÀ TINH THẦN",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay sức khỏe - du lịch sức khỏe: tầm nhìn mới cho kỷ nguyên chăm sóc thể chất và tinh thần. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-02-18",
    image: "/images/fs-outdoor-field.jpg",
    readTime: 15,
  },
  {
    slug: "farmstay-tren-bien-bien-bien-bac-thanh-tai-san-va-dong-tien-khac-biet",
    title: "FARMSTAY TRÊN BIỂN: BIẾN \"BIỂN BẠC\" THÀNH TÀI SẢN VÀ DÒNG TIỀN KHÁC BIỆT",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay trên biển: biến \"biển bạc\" thành tài sản và dòng tiền khác biệt. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Tài Chính",
    date: "2026-02-19",
    image: "/images/fs-interview-mountain.jpg",
    readTime: 13,
  },
  {
    slug: "farmstay-thu-cung-danh-trung-noi-dau-thi-truong-ngach-va-chien-luoc-hut-tien-tu-",
    title: "FARMSTAY THÚ CƯNG: ĐÁNH TRÚNG \"NỖI ĐAU\" THỊ TRƯỜNG NGÁCH VÀ CHIẾN LƯỢC HÚT TIỀN TỪ GIỚI TRẺ",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay thú cưng: đánh trúng \"nỗi đau\" thị trường ngách và chiến lược hút tiền từ giới trẻ. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-02-20",
    image: "/images/portrait-stage-1.jpg",
    readTime: 15,
  },
  {
    slug: "farmstay-chan-nuoi-tao-dong-tien-tu-nhung-trai-nghiem-chuyen-sau-doc-ban",
    title: "FARMSTAY CHĂN NUÔI, TẠO DÒNG TIỀN TỪ NHỮNG TRẢI NGHIỆM CHUYÊN SÂU ĐỘC BẢN",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay chăn nuôi, tạo dòng tiền từ những trải nghiệm chuyên sâu độc bản. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Tài Chính",
    date: "2026-02-21",
    image: "/images/outdoor-2-garden-speaking.jpg",
    readTime: 13,
  },
  {
    slug: "farmstay-spa-khang-dinh-thuong-hieu-dan-dat-nganh-lam-dep",
    title: "FARMSTAY SPA, KHẲNG ĐỊNH THƯƠNG HIỆU DẪN DẮT NGÀNH LÀM ĐẸP",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay spa, khẳng định thương hiệu dẫn dắt ngành làm đẹp. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Marketing",
    date: "2026-02-23",
    image: "/images/outdoor-1-mountain-tea.jpg",
    readTime: 11,
  },
  {
    slug: "farmstay-the-thao-khi-luyen-tap-o-noi-nong-nghiep-ben-vung",
    title: "FARMSTAY THỂ THAO, KHI LUYỆN TẬP Ở NƠI NÔNG NGHIỆP BỀN VỮNG",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay thể thao, khi luyện tập ở nơi nông nghiệp bền vững. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-02-24",
    image: "/images/fs-portrait-bamboo.jpg",
    readTime: 11,
  },
  {
    slug: "co-mot-yeu-to-nay-ban-se-lam-nen-thanh-cong-farmstay",
    title: "CÓ MỘT YẾU TỐ NÀY BẠN SẼ LÀM NÊN THÀNH CÔNG FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: có một yếu tố này bạn sẽ làm nên thành công farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-02-25",
    image: "/images/outdoor-3-forest-stream.jpg",
    readTime: 11,
  },
  {
    slug: "ba-tru-cot-nguon-luc-xay-dung-farmstay-luat-choi-song-phang-de-hop-tac-khong-do-",
    title: "BA TRỤ CỘT NGUỒN LỰC XÂY DỰNG FARMSTAY: LUẬT CHƠI SÒNG PHẲNG ĐỂ HỢP TÁC KHÔNG ĐỔ VỠ",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: ba trụ cột nguồn lực xây dựng farmstay: luật chơi sòng phẳng để hợp tác không đổ vỡ. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-02-26",
    image: "/images/fs-windmill.jpg",
    readTime: 14,
  },
  {
    slug: "farmstay-co-may-in-tien-kep-va-chien-luoc-phat-trien-ben-vung",
    title: "FARMSTAY: CỖ MÁY IN TIỀN KÉP VÀ CHIẾN LƯỢC PHÁT TRIỂN BỀN VỮNG",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay: cỗ máy in tiền kép và chiến lược phát triển bền vững. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Tài Chính",
    date: "2026-02-27",
    image: "/images/outdoor-4-waterfall.jpg",
    readTime: 12,
  },
  {
    slug: "10-tieu-chi-chon-dat-lam-farmstay-quyet-dinh-thanh-bai-dung-de-sai-lam-tu-buoc-c",
    title: "10 TIÊU CHÍ CHỌN ĐẤT LÀM FARMSTAY QUYẾT ĐỊNH THÀNH BẠI: ĐỪNG ĐỂ SAI LẦM TỪ BƯỚC CHÂN ĐẦU TIÊN",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: 10 tiêu chí chọn đất làm farmstay quyết định thành bại: đừng để sai lầm từ bước chân đầu tiên. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2026-02-28",
    image: "/images/outdoor-5-garden-chair.jpg",
    readTime: 15,
  },
  {
    slug: "10-tieu-chi-chon-dat-lam-farmstay-quyet-dinh-thanh-bai-dung-de-sai-lam-tu-buoc-c-2",
    title: "10 TIÊU CHÍ CHỌN ĐẤT LÀM FARMSTAY QUYẾT ĐỊNH THÀNH BẠI: ĐỪNG ĐỂ SAI LẦM TỪ BƯỚC CHÂN ĐẦU TIÊN",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: 10 tiêu chí chọn đất làm farmstay quyết định thành bại: đừng để sai lầm từ bước chân đầu tiên. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2026-03-03",
    image: "/images/fs-outdoor-field.jpg",
    readTime: 15,
  },
  {
    slug: "nguyen-tac-chien-luoc-5-quy-tac-vang-de-phat-trien-farmstay-ben-vung",
    title: "NGUYÊN TẮC CHIẾN LƯỢC: 5 QUY TẮC VÀNG ĐỂ PHÁT TRIỂN FARMSTAY BỀN VỮNG",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: nguyên tắc chiến lược: 5 quy tắc vàng để phát triển farmstay bền vững. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-05",
    image: "/images/fs-interview-mountain.jpg",
    readTime: 12,
  },
  {
    slug: "farmstay-cu-bat-tay-khoi-sinh-giua-chuyen-mon-nong-nghiep-va-nghe-thuat-du-lich",
    title: "FARMSTAY: CÚ BẮT TAY KHỞI SINH GIỮA CHUYÊN MÔN NÔNG NGHIỆP VÀ NGHỆ THUẬT DU LỊCH",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: farmstay: cú bắt tay khởi sinh giữa chuyên môn nông nghiệp và nghệ thuật du lịch. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-07",
    image: "/images/portrait-stage-1.jpg",
    readTime: 14,
  },
  {
    slug: "nghe-thuat-quy-tu-nguon-luc-dia-phuong-tu-cong-dong-ban-dia-den-farmstay-phat-tr",
    title: "NGHỆ THUẬT QUY TỤ NGUỒN LỰC ĐỊA PHƯƠNG: TỪ CỘNG ĐỒNG BẢN ĐỊA ĐẾN FARMSTAY PHÁT TRIỂN BỀN VỮNG",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: nghệ thuật quy tụ nguồn lực địa phương: từ cộng đồng bản địa đến farmstay phát triển bền vững. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Cộng Đồng",
    date: "2026-03-08",
    image: "/images/outdoor-2-garden-speaking.jpg",
    readTime: 15,
  },
  {
    slug: "chien-luoc-dai-du-an-farmstay-nhieu-phan-khu-va-phuc-vu-da-phan-khuc",
    title: "CHIẾN LƯỢC ĐẠI DỰ ÁN FARMSTAY, NHIỀU PHÂN KHU VÀ PHỤC VỤ ĐA PHÂN KHÚC",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: chiến lược đại dự án farmstay, nhiều phân khu và phục vụ đa phân khúc. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-09",
    image: "/images/outdoor-1-mountain-tea.jpg",
    readTime: 12,
  },
  {
    slug: "chuoi-farmstay-nhieu-diem-tao-lap-he-sinh-thai-du-lich-nong-nghiep",
    title: "CHUỖI FARMSTAY NHIỀU ĐIỂM, TẠO LẬP HỆ SINH THÁI DU LỊCH NÔNG NGHIỆP",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: chuỗi farmstay nhiều điểm, tạo lập hệ sinh thái du lịch nông nghiệp. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-10",
    image: "/images/fs-portrait-bamboo.jpg",
    readTime: 12,
  },
  {
    slug: "so-sanh-farmstay-va-homestay-giai-ma-loi-mo-hinh-va-lua-chon-dinh-huong-dau-tu",
    title: "SO SÁNH FARMSTAY VÀ HOMESTAY: GIẢI MÃ LÕI MÔ HÌNH VÀ LỰA CHỌN ĐỊNH HƯỚNG ĐẦU TƯ",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: so sánh farmstay và homestay: giải mã lõi mô hình và lựa chọn định hướng đầu tư. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-12",
    image: "/images/outdoor-3-forest-stream.jpg",
    readTime: 13,
  },
  {
    slug: "phan-biet-farmstay-va-ecolodge",
    title: "PHÂN BIỆT FARMSTAY VÀ ECOLODGE",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: phân biệt farmstay và ecolodge. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-17",
    image: "/images/fs-windmill.jpg",
    readTime: 9,
  },
  {
    slug: "phan-biet-farmstay-va-ecostay-hieu-dung-ban-chat-de-hoach-dinh-dau-tu-va-van-han",
    title: "PHÂN BIỆT FARMSTAY VÀ ECOSTAY: HIỂU ĐÚNG BẢN CHẤT ĐỂ HOẠCH ĐỊNH ĐẦU TƯ VÀ VẬN HÀNH HIỆU QUẢ",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: phân biệt farmstay và ecostay: hiểu đúng bản chất để hoạch định đầu tư và vận hành hiệu quả. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-19",
    image: "/images/outdoor-4-waterfall.jpg",
    readTime: 15,
  },
  {
    slug: "so-sanh-chi-tiet-mo-hinh-nghi-duong-farmstay-va-foreststay-duoi-lang-kinh-hoach-",
    title: "SO SÁNH CHI TIẾT MÔ HÌNH NGHỈ DƯỠNG: FARMSTAY VÀ FORESTSTAY DƯỚI LĂNG KÍNH HOẠCH ĐỊNH",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: so sánh chi tiết mô hình nghỉ dưỡng: farmstay và foreststay dưới lăng kính hoạch định. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-20",
    image: "/images/outdoor-5-garden-chair.jpg",
    readTime: 14,
  },
  {
    slug: "5-bo-loc-anh-em-bat-buoc-phai-danh-gia-truoc-khi-xuong-tien-dau-tu-farmstay",
    title: "5 BỘ LỌC ANH EM BẮT BUỘC PHẢI ĐÁNH GIÁ TRƯỚC KHI XUỐNG TIỀN ĐẦU TƯ FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: 5 bộ lọc anh em bắt buộc phải đánh giá trước khi xuống tiền đầu tư farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-21",
    image: "/images/fs-outdoor-field.jpg",
    readTime: 13,
  },
  {
    slug: "phan-biet-farmstay-va-glamping-lua-chon-chien-luoc-cho-nha-dau-tu",
    title: "PHÂN BIỆT FARMSTAY VÀ GLAMPING: LỰA CHỌN CHIẾN LƯỢC CHO NHÀ ĐẦU TƯ",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: phân biệt farmstay và glamping: lựa chọn chiến lược cho nhà đầu tư. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-21",
    image: "/images/fs-interview-mountain.jpg",
    readTime: 12,
  },
  {
    slug: "quy-hoach-farmstay-khong-chi-la-phan-chia-dat-dai-do-la-muu-luoc-chien-luoc",
    title: "QUY HOẠCH FARMSTAY: KHÔNG CHỈ LÀ PHÂN CHIA ĐẤT ĐAI, ĐÓ LÀ MƯU LƯỢC CHIẾN LƯỢC",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: quy hoạch farmstay: không chỉ là phân chia đất đai, đó là mưu lược chiến lược. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Thiết Kế",
    date: "2026-03-22",
    image: "/images/portrait-stage-1.jpg",
    readTime: 13,
  },
  {
    slug: "chon-loi-vao-chinh-cho-farmstay-nghe-thuat-dan-dat-cam-xuc",
    title: "CHỌN LỐI VÀO CHÍNH CHO FARMSTAY: NGHỆ THUẬT DẪN DẮT CẢM XÚC",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: chọn lối vào chính cho farmstay: nghệ thuật dẫn dắt cảm xúc. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Thiết Kế",
    date: "2026-03-24",
    image: "/images/outdoor-2-garden-speaking.jpg",
    readTime: 11,
  },
  {
    slug: "thiet-ke-truc-duong-trong-farmstay-nghe-thuat-quy-hoach-trai-nghiem-va-muu-luoc-",
    title: "THIẾT KẾ TRỤC ĐƯỜNG TRONG FARMSTAY: NGHỆ THUẬT QUY HOẠCH TRẢI NGHIỆM VÀ MƯU LƯỢC VẬN HÀNH",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: thiết kế trục đường trong farmstay: nghệ thuật quy hoạch trải nghiệm và mưu lược vận hành. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Thiết Kế",
    date: "2026-03-28",
    image: "/images/outdoor-1-mountain-tea.jpg",
    readTime: 14,
  },
  {
    slug: "co-hoi-va-tam-nhin-cho-du-lich-nong-nghiep-viet-nam-tu-khung-hoang-toan-cau-den-",
    title: "CƠ HỘI VÀ TẦM NHÌN CHO DU LỊCH NÔNG NGHIỆP VIỆT NAM: TỪ KHỦNG HOẢNG TOÀN CẦU ĐẾN ĐÔ THỊ NÔNG NGHIỆP",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: cơ hội và tầm nhìn cho du lịch nông nghiệp việt nam: từ khủng hoảng toàn cầu đến đô thị nông nghiệp. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Chiến Lược",
    date: "2026-03-29",
    image: "/images/fs-portrait-bamboo.jpg",
    readTime: 15,
  },
  {
    slug: "duong-trong-farm-truyen-tai-chien-luoc-cua-farmstay",
    title: "ĐƯỜNG TRONG FARM TRUYỀN TẢI CHIẾN LƯỢC CỦA FARMSTAY",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: đường trong farm truyền tải chiến lược của farmstay. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Thiết Kế",
    date: "2026-04-01",
    image: "/images/outdoor-3-forest-stream.jpg",
    readTime: 11,
  },
  {
    slug: "chon-dat-lam-farmstay-muu-luoc-ung-pho-voi-nhung-bat-thuong-cua-khi-hau",
    title: "CHỌN ĐẤT LÀM FARMSTAY: MƯU LƯỢC ỨNG PHÓ VỚI NHỮNG BẤT THƯỜNG CỦA KHÍ HẬU",
    excerpt: "Bài viết chia sẻ góc nhìn thực chiến về: chọn đất làm farmstay: mưu lược ứng phó với những bất thường của khí hậu. Kiến thức được đúc kết từ hàng trăm dự án farmstay và du lịch nông nghiệp trên toàn Việt Nam.",
    category: "Đất Đai",
    date: "2026-04-02",
    image: "/images/fs-windmill.jpg",
    readTime: 13,
  },
];
