// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Local dev: file:./dev.db (SQLite)
    // Production: postgresql://... (Neon / Supabase / Railway)
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
